# Generated by Django 4.1.6 on 2023-02-10 14:02

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='number',
            field=models.CharField(default=main.utils.get_order_number, max_length=32, unique=True, verbose_name='Número do pedido'),
        ),
    ]
